export function onRequest(context) {
    // return new Response(
    //     context.request.url
    // );
    return new Response(
        'Hello, this response is generated by Cloudflare Pages Functions.'
    );
};
